name: Angular CI and Coverage Report

on:
  push:
    branches:
      - master
      - dev/*
  pull_request:
    branches:
      - master
      - dev/*

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ng-toolkit # Modifiez ce chemin selon vos besoins

    strategy:
      matrix:
        node-version: [16.x] # Utilisez une version LTS pour Angular

    steps:
      # Étape 1 : Cloner le dépôt
      - uses: actions/checkout@v2

      # Étape 2 : Configurer Node.js
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Étape 3 : Installer les dépendances
      - name: Install dependencies
        run: npm ci

      # Étape 4 : Exécuter les tests avec couverture
      - name: Run Tests and Generate Coverage
        run: npm run test:prod -- --code-coverage

      # Étape 5 : Linter le code
      - name: Run Lint
        run: npm run lint

      # Étape 6 : Upload des rapports de couverture (si nécessaire)
      - name: Upload Coverage Report
        uses: actions/upload-artifact@v2
        with:
          name: frontend-coverage-report
          path: coverage
